### ISSUE TITLE
Saved pictures are not scraping.

### ISSUE THREAD

**Issue by sk8higher** [vanyasem/VK-Scraper#3]
I tried to download photos from my profile, but scraper didn't download photos from Saved photos' album. Then I tried to change my privacy settings, but that didn't help.

**Comment by vanyasem** [comment]
Sadly [photos.getAll](https://vk.com/dev/photos.getAll) method from the VK's API doesn't support returning saved pictures. This requires implementing a new media type called "saved" to be used with [photos.get](https://vk.com/dev/photos.get). I guess that makes sense, as people usually save trash in this album. I'm on it

**Comment by vanyasem** [comment]
Implemented. New media type `saved`.
```
Searching REDACTED for saved pictures: 2292 pictures [00:01, 1591.75 pictures/s]
Downloading:  18%|█▊        | 418/2292 [00:05<00:22, 81.77it/s]
```
