### ISSUE TITLE
Scraping Communities Data?

### ISSUE THREAD

**Issue by JDiaz11** [vanyasem/VK-Scraper#7]
Hello-- the app description states "vk-scraper is a command-line application written in Python that scrapes and downloads VK user's / community's data. Use responsibly" but when I add the name of the community to the command as 'VK-Scraper @vk_args.txt [community_name]' or the list file as 'VK-Scraper @vk_args.txt -f vk_users.txt' I get the error: 'Error getting user details for [community_name]' Is the feature not working or am I doing something incorrectly?

**Comment by estatistics** [comment]
I cant download community photos, even disabling 2 step verification. 
"Unknown API auth error -- ERROR: Login failed for xxxxxxxxx"

I used also single-app passwords but failed.

**Comment by vanyasem** [comment]
@estatistics your issue is unrelated to this bug, it was a separate bug: https://github.com/vanyasem/VK-Scraper/issues/9

**Comment by vanyasem** [comment]
Fixed in #10
